class Chain
{
public static void main(String[] args)
{
String urNo="my no is 24";
System.out.println(urNo);
String urName="my name is swetha";
System.out.println(urName);
String urGood="yes iam good";
System.out.println(urGood);
String urNice="ofcourse";
System.out.println(urNice);
String password="me is a good";
System.out.println(password);
String urThin="ur so week";
System.out.println(urThin);
String pleaswGo="u getout";
System.out.println(pleaswGo);
String uGo="yes i will go";
System.out.println(uGo);
String pleaseDance="yes i can dance";
System.out.println(pleaseDance);
String fine="yaa iam fier";
System.out.println(fine);
String keywords="my keywords is good";
System.out.println(keywords);
String nameIs="my name is nice";
System.out.println(nameIs);
String myGod="oh my god";
System.out.println(myGod);
String goBack="please go back yar";
System.out.println(goBack);
String canUSing="ya ma i sing";
System.out.println(canUSing);
String noCant="no i cant do that";
System.out.println(noCant);
String putBed="y u cant do";
System.out.println(putBed);
String bedSheet="go to bedsheet";
System.out.println(bedSheet);
String classess="go to the classess";
System.out.println(classess);
String daughter="she is my daughter";
System.out.println(daughter);
String westSide="my west is u";
System.out.println(westSide);
String eastSide="my east is west";
System.out.println(eastSide);
String bestPart="ur my bestpart";
System.out.println(bestPart);
String couldyou="can u come";
System.out.println(couldyou);
String noICould="no yar i go";
System.out.println(noICould);
String laptop="my lap is fine";
System.out.println(laptop);
String computer="my computer is good";
System.out.println(computer);
String system="my system is 100";
System.out.println(system);
String mouse="my mouse is working";
System.out.println(mouse);
String cpuCant="my cpu can do";
System.out.println(cpuCant);
String readBook="my book is good";
System.out.println(readBook);
String noReading="my number is lost";
System.out.println(noReading);
String ySo="y u cant";
System.out.println(ySo);
String pleaseCome="come to class regular";
System.out.println(pleaseCome);
String window="window is open";
System.out.println(window);
String penDrive="my drive is good";
System.out.println(penDrive);
String cd="my cd can work";
System.out.println(cd);
String css="my css can work";
System.out.println(css);
String newWay="my way is new";
System.out.println(newWay);
String noWay="no wy can do this";
System.out.println(noWay);
String bagPack="go and pack ur bag";
System.out.println(bagPack);
String goodOne="ur so good one";
System.out.println(goodOne);
String yesUDo="yes i can do for that";
System.out.println(yesUDo);
String hairGrowth="my hair not growing";
System.out.println(hairGrowth);
String cothBag="bag is to heavy";
System.out.println(cothBag);
String common="ur so common";
System.out.println(common);
String selfRespect="i have m selfrespect";
System.out.println(selfRespect);
String giveBook="book give here";
System.out.println(giveBook);
String seeU="my no is 24";
System.out.println(seeU);
String noSee="my name is swetha";
System.out.println(noSee);
String uBad="yes iam good";
System.out.println(uBad);
String stick="ofcourse";
System.out.println(stick);
String noStick="me is a good";
System.out.println(noStick);
String ohMyGod="ur so week";
System.out.println(ohMyGod);
String comeGoo="u getout";
System.out.println(comeGoo);
String uGooo="yes i will go";
System.out.println(uGooo);
String pleaseDanceee="yes i can dance";
System.out.println(pleaseDanceee);
String fineee="yaa iam fier";
System.out.println(fineee);
String keywordsss="my keywords is good";
System.out.println(keywordsss);
String nameIsss="my name is nice";
System.out.println(nameIsss);
String myGoddd="oh my god";
System.out.println(myGoddd);
String goBackkk="please go back yar";
System.out.println(goBackkk);
String canUSinggg="ya ma i sing";
System.out.println(canUSinggg);
String noCanttt="no i cant do that";
System.out.println(noCanttt);
String putBeddd="y u cant do";
System.out.println(putBeddd);
String bedSheettt="go to bedsheet";
System.out.println(bedSheettt);
String classesss="go to the classess";
System.out.println(classesss);
String daughterr="she is my daughter";
System.out.println(daughterr);
String westSidee="my west is u";
System.out.println(westSidee);
String eastSidee="my east is west";
System.out.println(eastSidee);
String bestPartt="ur my bestpart";
System.out.println(bestPartt);
String couldyouu="can u come";
System.out.println(couldyouu);
String noICouldd="no yar i go";
System.out.println(noICouldd);
String laptopp="my lap is fine";
System.out.println(laptopp);
String computerr="my computer is good";
System.out.println(computerr);
String systemm="my system is 100";
System.out.println(systemm);
String mousee="my mouse is working";
System.out.println(mousee);
String cpuCantt="my cpu can do";
System.out.println(cpuCantt);
String readBookk="my book is good";
System.out.println(readBookk);
String noReadingg="my number is lost";
System.out.println(noReadingg);
String ySoo="y u cant";
System.out.println(ySoo);
String pleaseComee="come to class regular";
System.out.println(pleaseComee);
String windoww="window is open";
System.out.println(windoww);
String penDrivee="my drive is good";
System.out.println(penDrivee);
String cdd="my cd can work";
System.out.println(cdd);
String csss="my css can work";
System.out.println(csss);
String newWayy="my way is new";
System.out.println(newWayy);
String noWayy="no wy can do this";
System.out.println(noWayy);
String bagPackk="go and pack ur bag";
System.out.println(bagPackk);
String goodOnee="ur so good one";
System.out.println(goodOnee);
String yesUDoo="yes i can do for that";
System.out.println(yesUDoo);
String hairGrowthhhh="my hair not growing";
System.out.println(hairGrowthhhh);
String cothBagggg="bag is to heavy";
System.out.println(cothBagggg);
String commonnnn="ur so common";
System.out.println(commonnnn);
String selfRespectttt="i have m selfrespect";
System.out.println(selfRespectttt);
String giveBookkkk="book give here";
System.out.println(giveBookkkk);
String ySoooo="y u cant";
System.out.println(ySoooo);
String pleaseComeeee="come to class regular";
System.out.println(pleaseComeeee);
String windowwww="window is open";
System.out.println(windowwww);
String penDriveeee="my drive is good";
System.out.println(penDriveeee);
String cdddd="my cd can work";
System.out.println(cdddd);
String csssss="my css can work";
System.out.println(csssss);
String newWayyyy="my way is new";
System.out.println(newWayyyy);
String noWayyyy="no wy can do this";
System.out.println(noWayyyy);
String bagPackkkk="go and pack ur bag";
System.out.println(bagPackkkk);
}
}